fix: fix id_or_name property of key class
googleapis/python-datastore pull request #115
Opened 2020-11-09 10:39 UTC by HemangChothani

Fixes #106

2020-11-09 14:02 UTC, chrisrossi commented
Does Datastore let you store a key with id of ``0``?

2020-11-10 04:46 UTC, HemangChothani commented
@chrisrossi Library doesn't stop or raise error when passing id =0 but  `if id is  0, generate automatically` as mentioned in document [here](https://cloud.google.com/appengine/docs/standard/go111/datastore/creating-entity-keys#specifying_a_key_name_for_an_entity)

2020-11-10 13:48 UTC, chrisrossi commented
> @chrisrossi Library doesn't raise an error when passing id =0 but `if id is 0, generate automatically` as mentioned in document [here](https://cloud.google.com/appengine/docs/standard/go111/datastore/creating-entity-keys#specifying_a_key_name_for_an_entity)

Fair enough! This looks good to me, but I would probably add a regression test.

2020-11-11 17:09 UTC, tseaver requested changes

2020-11-11 17:09 UTC, tseaver commented on google/cloud/datastore/key.py
> +        return self.id
Please add a unit test exercising #106 (i.e., set the key's `id` to 0 and assert that `id_or_name` returns the 0).

2020-11-12 22:12 UTC, tseaver approved these changes

2020-11-13 20:30 UTC, tseaver commented
@crwilcox, @czahedi Again, the `requiresCodeOwnerReviews: true` policy means my approval is not sufficient to merge this PR.

2020-11-13 20:46 UTC, crwilcox approved these changes

2020-11-13 20:46 UTC, merged