chore: migrate to owl bot
googleapis/python-datastore pull request #170
Opened 2021-05-12 14:04 UTC by parthea

This PR migrates from autosynth to [owl bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/owl-bot).  owl bot will save time for maintainers as it will automatically open PRs when there are updates in [googleapis-gen](https://github.com/googleapis/googleapis-gen/tree/master/google) without requiring maintainers to run `synthtool` to build the client from protos. Additionally, similar to autosynth, PRs will be automatically opened when there are template updates.

2021-05-12 20:16 UTC, tseaver requested changes

2021-05-12 20:16 UTC, tseaver commented on owlbot.py
> +
This change is no longer correct after applying the generation of `CONTRIBUTING.rst` above:  see PR #166.

2021-05-18 16:17 UTC, tseaver approved these changes

2021-05-18 17:44 UTC, parthea commented
I'd like to put this one on hold for a day while I investigate why the owl bot migration script didn't copy code from `googleapis-gen`

2021-05-21 17:27 UTC, busunkim96 approved these changes

2021-05-25 15:46 UTC, parthea commented
I couldn't get to the bottom of why the migration script is failing. I'm going to run the commands manually to migrate this repo.

2021-05-25 16:15 UTC, tseaver approved these changes

2021-05-25 16:44 UTC, tseaver commented
Coverage is failing (under 100%) due to https://github.com/googleapis/gapic-generator-python/issues/632.

2021-06-07 19:09 UTC, busunkim96 commented
It looks like the remaining coverage drops were from a combo of (1) lost replacements in noxfile.py (2) missing pytest-asyncio. On the latest commit I was able to get 100% coverage.

2021-06-07 19:56 UTC, merged