Add samples for IN, NOT_IN, and != operators.
googleapis/python-datastore pull request #312
Opened 2022-05-24 21:05 UTC by jlara310

Add samples for IN, NOT_IN, and != operators.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-datastore/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #311 🦕

2022-05-24 23:20 UTC, jlara310 commented
Depends on #287

2022-05-25 22:59 UTC, Mariatta requested changes

2022-05-25 22:59 UTC, Mariatta commented on samples/snippets_test.py
> +@pytest.yield_fixture
I'm seeing `PytestDeprecationWarning` on this line.
Can you please change it to `@pytest.fixture`?

> Warning: @pytest.yield_fixture is deprecated.
Use @pytest.fixture instead; they are the same.
  def client():
```suggestion
@pytest.fixture
```

2022-06-10 06:21 UTC, jlara310 commented
Now that #287 merged, this is ready for review/merge, too.

2022-06-10 07:04 UTC, jlara310 commented
The project used for testing requires the indexes in samples/index.yaml. Can someone help me add that index to the testing project?

`gcloud datastore create index.yaml`

2022-06-10 18:29 UTC, Mariatta commented
It seems that I also don't have the permission to create the index. I'm trying to find out who could create the index for us.

2022-06-10 19:42 UTC, Mariatta commented
The index is now being served, however it doesn't seem like the samples tests are being run as part of the CI.

2022-06-10 19:43 UTC, Mariatta commented on samples/snippets.py
> +import datetime
These two lines seems to be not used.

2022-06-10 19:43 UTC, Mariatta commented on samples/snippets.py
> +from google.cloud import datastore  # noqa: I100
This is also not used.

2022-06-10 19:48 UTC, Mariatta commented on samples/snippets_test.py
> +        assert tasks
```suggestion
        assert tasks is not None
```

2022-06-10 19:49 UTC, Mariatta commented on samples/snippets.py
> +def not_equals_query(client):
Duplicated test.

```suggestion
def not_in_query(client):
```

2022-06-10 19:50 UTC, Mariatta commented on samples/snippets_test.py
> +        assert tasks
```suggestion
        assert tasks is not None
```

2022-06-10 19:50 UTC, Mariatta commented on samples/snippets_test.py
> +        assert tasks
```suggestion
        assert tasks is not None
```

2022-06-10 19:50 UTC, Mariatta commented on samples/snippets_test.py
> +        assert tasks
```suggestion
        assert tasks is not None
```

2022-06-10 19:50 UTC, Mariatta commented on samples/snippets_test.py
> +        assert tasks
```suggestion
        assert tasks is not None
```

2022-06-10 20:41 UTC, Mariatta commented
Ok looks like the samples tests are now running, and there are some errors.

2022-06-13 19:43 UTC, jlara310 commented
Looks like it's just python-docs-samples-tests that is on the legacy back-end. The build-specific projects look to be on Firestore in Datastore mode. Opting into those in the noxfile to use them for testing.

2022-06-15 02:48 UTC, jlara310 commented
Added a test fixture to set up the required index if it doesn't already exist. However, I'm now getting this error when attempting to create that index:

"google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission"

Either I didn't set things up quite right or the service account doesn't have index creation permissions on the build-specific test projects.

2022-06-15 05:40 UTC, jlara310 commented
I removed the snippets that require an index for now. I'd like to submit the remaining snippets as that will allow me to update the documentation. I can figure out the other two snippets in a follow-up PR.

I'm still failing two checks, but I'm not sure why. Any insights, appreciated.

Kokoro — Build failed error:

nox > * docs: failed

Kokoro Prerelease Dependencies error:

ERROR collecting samples/snippets/snippets_test.py 
Traceback:
/usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
samples/snippets/snippets_test.py:16: in <module>
    import backoff
E   ModuleNotFoundError: No module named 'backoff'

2022-06-16 15:47 UTC, jlara310 commented
PR should be good to go and ready to merge. Thank you.

2022-06-16 19:20 UTC, Mariatta commented on samples/snippets/snippets.py
> +        print(name)
Just wondering what is the purpose of the prints here?

One of the output is for the `pprint`:

```
pprint
<google.cloud.datastore.client.Client object at 0x1096a7820>
None
```

Perhaps we don't need these prints?

2022-06-16 19:29 UTC, Mariatta approved these changes

2022-06-16 19:30 UTC, Mariatta commented
The pre-release dependencies CI is not needed so it's good to merge. Thank you!

2022-06-16 19:32 UTC, merged